# Creating NumPy Arrays

# Arrays

In [ ]:
import numpy as np
x =[1, 2, 3, 4]
y = np.array(x)
print(y)
print(type(y)) 
print(y.ndim) # Used for find dimension of the Array.

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
l = []
for i in range(1,5):
    a = int(input("Enter Element : "))
    l.append(a)
print(np.array(l))
    

In [ ]:
ar2 = np.array([[1, 2, 3, 4],[5, 2, 4, 9]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 2 4 9]]
2


In [ ]:
arr3 = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
a = np.array([3, 1, 3], ndmin=10)   # ndmin use for give the value of Dimension.
print(a)
print(a.ndim)

[[[[[[[[[[3 1 3]]]]]]]]]]
10


# Zeros

In [ ]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [ ]:
ar_zeros2d = np.zeros((3,2))
print(ar_zeros2d)
print(ar_zeros2d.ndim)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
2


# Ones

In [ ]:
ar_one = np.ones(5)
print(ar_one)
print(ar_one.ndim)

[1. 1. 1. 1. 1.]
1


# Empty

In [ ]:
ar_emp = np.empty(4)
print(ar_emp)
print(ar_emp.ndim)

[0. 0. 0. 0.]
1


# Range

In [ ]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [6]:
import numpy as np
ar_dia = np.eye(5)   # eye() used for diagonal value.
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)   # eye() used for diagonal value.
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# LineSapce

In [ ]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Creating NumPy Array With Random Number

# Random

## rand()

In [ ]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.9757153  0.68687066 0.66889849 0.01991453]


In [ ]:
#[0.9757153  0.68687066 0.66889849 0.01991453]
var1 = np.random.rand(2,5)
print(var1)

[[0.92802243 0.70174574 0.59073852 0.26081237 0.03916476]
 [0.79588833 0.81963372 0.68555104 0.35492349 0.22285982]]


## randn()

In [ ]:
import numpy as np
var = np.random.randn(5)
print(var)

[ 1.69094054  1.86526873 -1.01650725  1.17102752  0.46874968]


## ranf()

In [ ]:
var3 = np.random.ranf(4)
print(var3)

[0.0090898  0.16754649 0.24525491 0.22728081]


## randint()

In [ ]:
var4 = np.random.randint(5,20,5)  # m in value, max value, total value
print(var4)

[14 11  7 11  9]


# DATA TYPES

In [ ]:
import numpy as np
var = np.array([1, 2, 3, 4])
print(var)
print("Data Type : ",var.dtype)

[1 2 3 4]
Data Type :  int32


In [ ]:
var = np.array([1.3, 2.7, 3.2, 4.0])
print(var)
print("Data Type : ",var.dtype)

[1.3 2.7 3.2 4. ]
Data Type :  float64


In [ ]:
var = np.array(["E", "R", "R", "O", "R"])
print(var)
print("Data Type : ",var.dtype)

['E' 'R' 'R' 'O' 'R']
Data Type :  <U1


In [ ]:
var = np.array(["E", "R", "R", "O", "R", 3, 1, 3])
print(var)
print("Data Type : ",var.dtype)

['E' 'R' 'R' 'O' 'R' '3' '1' '3']
Data Type :  <U11


In [ ]:
x = np.array([3, 1, 3])
print(x)
print("Data Type : ",x.dtype)

[3 1 3]
Data Type :  int32


In [ ]:
x = np.array([3, 1, 3], dtype = np.int8)
print(x)
print("Data Type : ",x.dtype)

[3 1 3]
Data Type :  int8


In [ ]:
x = np.array([3, 1, 3], dtype ="f")
print(x)
print("Data Type : ",x.dtype)

[3. 1. 3.]
Data Type :  float32


In [ ]:
import numpy as np
x = np.array([3, 1, 3])
new = np.float32(x)
print(x)
print(new)
print("Data Type : ",x.dtype)
print("Data Type : ",new.dtype)

[3 1 3]
[3. 1. 3.]
Data Type :  int32
Data Type :  float32


In [ ]:
x = np.array([3, 1, 3])
new = np.float32(x)
new1 = np.int_(new)
print(x)
print(new)
print(new1)
print("Data Type : ",x.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new1.dtype)

[3 1 3]
[3. 1. 3.]
[3 1 3]
Data Type :  int32
Data Type :  float32
Data Type :  int32


In [ ]:
x = np.array([3, 1, 3])
new = x.astype(float)
print(x)
print(new)
print("Data Type : ",x.dtype)
print("Data Type : ",new.dtype)

[3 1 3]
[3. 1. 3.]
Data Type :  int32
Data Type :  float64


# Arithmetic Operations

## 1D Array

In [ ]:
import numpy as np
var = np.array([1, 2, 3, 4])
var_add = var+ 3
print(var_add)

[4 5 6 7]


In [ ]:
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])
var_add = var1 + var2
print(var_add)

[2 4 6 8]


In [ ]:
var = np.array([1, 2, 3, 4])
var_sub = var- 3
print(var_sub)

[-2 -1  0  1]


In [ ]:
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])
var_add = np.add(var1, var2)
print(var_add)

[2 4 6 8]


## 2D Array

In [ ]:
var1 = np.array([[1, 2, 3],[4, 5, 6]])
var2 = np.array([[5, 3, 2],[7, 9, 8]])
ans = np.add(var1,var2)
ans1 = np.multiply(var1,var2)
ans3 = np.reciprocal(var1)
print("Sum of va1 and var2 is : ",ans)
print()
print("Product of var1 and var2 is : ",ans1)
print()
print("Reciprocal of var1 is :",ans3)

Sum of va1 and var2 is :  [[ 6  5  5]
 [11 14 14]]

Product of var1 and var2 is :  [[ 5  6  6]
 [28 45 48]]

Reciprocal of var1 is : [[1 0 0]
 [0 0 0]]


# Arithmetic Functions

In [ ]:
var1 = np.array([3, 5, 2, 9, 8, 4])
print("Maximum value is : ",np.max(var1)," At position index : ",np.argmax(var1))
print("Minimum value is : ",np.min(var1)," At position index : ",np.argmin(var1))

Maximum value is :  9  At position index :  3
Minimum value is :  2  At position index :  2


In [ ]:
var1 = np.array([[2,1,9],[8,3,6]])
print(np.min(var1, axis=1))
print(np.max(var1, axis=1))
print(np.min(var1, axis=0))
print(np.max(var1, axis=0))

[1 3]
[9 8]
[2 1 6]
[8 3 9]


In [ ]:
var1 = np.array([16, 25, 12, 9, 8, 4])
print(np.sqrt(var1))

[4.         5.         3.46410162 3.         2.82842712 2.        ]


In [ ]:
var2 = np.array([1, 2, 3])
print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [ ]:
var3 = np.array([1, 2, 3, 4])
print(np.cumsum(var3))

[ 1  3  6 10]


# Shape And Reshaping

## Shape

In [ ]:
import numpy as np
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [ ]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)  # ndim used for size of Array.
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


## Reshape

In [ ]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
x =var2.reshape(2,3)
print()
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2 3]
 [4 5 6]]
2


In [ ]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
x1 =var3.reshape(4,3,1)
print()
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
3


In [ ]:
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# BroadCasting

## Rules for BroadCasting

### (1) Same Dimension.
### (2) Different Dimension same values.

In [ ]:
import numpy as np
var1 = np.array([1,2,3,4])
print(var1.shape)
var2 = np.array([1,2,3,4])
print(var2.shape)
print(var1 + var2)

(4,)
(4,)
[2 4 6 8]


In [ ]:
var3 = np.array([1,2,3,4])
print(var3)
print(var3.shape)
print()
var4 = np.array([[1],[2],[3],[4]])
print(var4)
print(var4.shape)
print()
print(var3 + var4)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [ ]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print()
print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing And Slicing

## Indexing

In [ ]:
import numpy as np
var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [ ]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [ ]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


## Slicing

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print(f"2 to 5 : {var[1:5]}")
print(f"2 to End : {var[1:]}")
print(f"Start to 5 : {var[:5]}")
print(f"Start to End : {var[::]}")

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to End : [2 3 4 5 6 7]
Start to 5 : [1 2 3 4 5]
Start to End : [1 2 3 4 5 6 7]


# Iteration

In [6]:
import numpy as np
var = np.array([9,8,7,6,5,4])
print(var)
for i in var:
    print(i)

[9 8 7 6 5 4]
9
8
7
6
5
4


In [14]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [16]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]]]

3

1
2
3
4
1
2
3
4


In [30]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()
for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

3

b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [32]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()
for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

3

9
8
7
6
1
2
3
4


In [40]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]

3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# #Copy vs View

In [52]:
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()
var[1] = 40
print("var : ",var)
print("copy : ",co)

var :  [ 1 40  3  4]
copy :  [1 2 3 4]


In [54]:
x = np.array([9,8,7,6])
vi = x.view()
x[1] = 40
print("x : ",x)
print("view : ",vi)

x :  [ 9 40  7  6]
view :  [ 9 40  7  6]


# Join AND Split Functions

## Join Array

In [58]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [76]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar1_new = np.concatenate((vr,vr1),axis=0)
ar_new = np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(vr1)
print()
print(ar1_new)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [78]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

ar_new = np.stack((var_1,var_2), axis = 1)
print(ar_new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [88]:
vr_1 = np.array([1,2,3,4])
vr_2 = np.array([9,8,7,6])

arr_new = np.stack((var_1,var_2), axis = 1)
print(arr_new)
print()
arr_new1 = np.hstack((vr_1,vr_2))   # Row
print(arr_new1)
print()
arr_new2 = np.vstack((vr_1,vr_2))  # Colums
print(arr_new2)
print()
arr_new3 = np.dstack((vr_1,vr_2)) # Hight
print(arr_new3)
print()

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]



## Split Array

In [113]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
print()
ar = np.array_split(var,3)
print(ar)
print(type(ar))
print()
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>

[1 2]


In [121]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
print()
ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis = 1)
print(ar1)
print(type(ar1))
print()
print(ar2)
print(type(ar2))
print()
print(ar1[2])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>

[[5 6]]


# Search, Sort, Search Sorted, Filter

## Search

In [133]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where(var == 2)
print(x)
y = np.where((var%2) == 0)
print(y)
z = np.where((var/2) == 0)
print(z)

(array([1, 4, 6], dtype=int64),)
(array([1, 3, 4, 6, 8], dtype=int64),)
(array([], dtype=int64),)


In [2]:
import numpy as np
print(np.__version__) 

1.26.4
