In [ ]:
1. Import numpy as np and see the version              Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
2. How to create a 1D array?

In [ ]:
Q. Create a 1D array of numbers from 0 to 9

Desired output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
3. How to create a boolean array?

In [ ]:
Q. Create a 3×3 numpy array of all True’s

In [24]:
import numpy as np
x = np.ones(9,bool).reshape(3,3)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
import numpy as np
x = np.ones((3,3),dtype=bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
import numpy as np 
x = np.full((3,3), True, dtype=bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
4. How to extract items that satisfy a given condition from 1D array?

In [ ]:
Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:

#> array([1, 3, 5, 7, 9])

In [42]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr1 = arr[arr%2 == 1]
print(arr1)

[1 3 5 7 9]


In [44]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[1::2])

[1 3 5 7 9]


In [ ]:
5. How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [50]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [70]:
6. How to replace items that satisfy a condition without affecting the original array?

Object `array` not found.


In [ ]:
Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
import numpy as np
arr = np.arange(10)
out = np.where(arr%2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
7. How to reshape an array?

In [ ]:
Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [86]:
import numpy as np
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
import numpy as np
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
8. How to stack two arrays vertically?

In [ ]:
Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [98]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [100]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [106]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# np.r_[a, b] concatenates the two 2-dimensional arrays a and b vertically (row-wi
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
9. How to stack two arrays horizontally?

In [ ]:
Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [110]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [114]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [120]:
import numpy as np
a = np.arange(10).reshape(2,-1)
print(a)
print()
b = np.repeat(1,10).reshape(2,-1)
print(b)
print()
np.c_[a,b]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
10. How to generate custom sequences in numpy without hardcoding?

In [ ]:
Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [134]:
import numpy as np
a = np.array([1,2,3])
print(np.hstack.repeat(a,3),a,a,a)

TypeError: hstack() takes 1 positional argument but 4 were given