In [12]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.concatenate((x,x1))
print(x2)

[1 2 3 4 5 6 7 8]


In [14]:
import numpy as np
x = np.array([[1, 2],[3, 4]])
x1 = np.array([[5, 6],[7, 8]])
x2 = np.concatenate((x,x1),axis=0)
print(x2)
x3 = np.concatenate((x,x1), axis=1)
print()
print(x3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.concatenate((x,x1),axis = 1)
print(x2)
x3 = np.concatenate((x,x1),axis = 0)
print(x3)

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.hstack((x,x1))
print(x2)

[1 2 3 4 5 6 7 8]


In [28]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.hstack((x,x1))
print(x2)


[[1 2 3 4 5 6 7 8]]


In [30]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.vstack((x,x1))
print(x2)


[[1 2 3 4]
 [5 6 7 8]]


In [32]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.vstack((x,x1))
print(x2)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
import numpy as np
x = np.array([[1, 2],[3, 4]])
x1 = np.array([[5, 6],[7, 8]])
x2 = np.hstack((x,x1))
print(x2)
x3 = np.vstack((x,x1))
print()
print(x3)
x4 = np.dstack((x,x1))
print()
print(x4)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [40]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.dstack((x,x1))
print(x2)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [52]:
import numpy as np
x = np.array([1,2,3,4,5,6])
x1 = np.array_split(x,3)
print(x1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [54]:
import numpy as np
x = np.array([1,2,3,4,5,6])
x1 = np.array_split(x,4)
print(x1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [60]:
import numpy as np
x = np.array([1,2,3,4,5,6])
x1 = np.array_split(x,3)
print(x1)
print(x1[1])
print()
print(x1[0])
print(x1[1])
print(x1[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]

[1 2]
[3 4]
[5 6]


In [62]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
x1 = np.array_split(x,3)
print(x1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [70]:
import numpy as np
x = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
x1 = np.array_split(x,2)
print(x1)
print()
x2 = np.array_split(x,3)
print(x2)

[array([[[1, 2],
        [3, 4],
        [5, 6]]]), array([[[ 7,  8],
        [ 9, 10],
        [11, 12]]])]

[array([[[1, 2],
        [3, 4],
        [5, 6]]]), array([[[ 7,  8],
        [ 9, 10],
        [11, 12]]]), array([], shape=(0, 3, 2), dtype=int32)]
