In [12]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.concatenate((x,x1))
print(x2)

[1 2 3 4 5 6 7 8]


In [14]:
import numpy as np
x = np.array([[1, 2],[3, 4]])
x1 = np.array([[5, 6],[7, 8]])
x2 = np.concatenate((x,x1),axis=0)
print(x2)
x3 = np.concatenate((x,x1), axis=1)
print()
print(x3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.concatenate((x,x1),axis = 1)
print(x2)
x3 = np.concatenate((x,x1),axis = 0)
print(x3)

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.hstack((x,x1))
print(x2)

[1 2 3 4 5 6 7 8]


In [28]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.hstack((x,x1))
print(x2)


[[1 2 3 4 5 6 7 8]]


In [30]:
import numpy as np
x = np.array([[1, 2, 3, 4]])
x1 = np.array([[5, 6, 7, 8]])
x2 = np.vstack((x,x1))
print(x2)


[[1 2 3 4]
 [5 6 7 8]]


In [32]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.vstack((x,x1))
print(x2)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
import numpy as np
x = np.array([[1, 2],[3, 4]])
x1 = np.array([[5, 6],[7, 8]])
x2 = np.hstack((x,x1))
print(x2)
x3 = np.vstack((x,x1))
print()
print(x3)
x4 = np.dstack((x,x1))
print()
print(x4)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [40]:
import numpy as np
x = np.array([1, 2, 3, 4])
x1 = np.array([5, 6, 7, 8])
x2 = np.dstack((x,x1))
print(x2)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
