# PART 1: 

## Create a 1D array of numbers from 0 to 9

In [39]:
import numpy as np
def function1():
    arr = np.arange(10)
    return arr 
print(function1())

[0 1 2 3 4 5 6 7 8 9]


## Extract all odd numbers from arr

In [43]:
def OddExtract():
    arr=function1()
    odd = arr[(arr%2!=0)]
    return odd
print(OddExtract())

[1 3 5 7 9]


## Replace all odd numbers in arr with -1

In [8]:
def OddReplace():
    arr=function1()
    arr[(arr%2==1)]=-1
    return arr
print(OddReplace())    

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## convert it back

In [53]:
arr = function1()
odd_indices = np.where(arr%2!=0)[0]
print(odd_indices)

[1 3 5 7 9]


In [10]:
def restoreOdd():
    arr = function1()
    odd_indices = np.where(arr%2!=0)[0]
    x = OddReplace()
    for i in odd_indices:
        x[i]=arr[i]
    return x
print(restoreOdd())

[0 1 2 3 4 5 6 7 8 9]


## Convert a 1D array to a 2D array with 2 rows

In [55]:
def OneDToTwoD():
    return function1().reshape(2,5)
print(OneDToTwoD())

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Stack arrays a and b vertically & Horizontally

In [57]:
def VerticalStack():
    return np.vstack(function1())
print(VerticalStack())
print()
def HorizantalStack():
    return np.hstack(function1())
print(HorizantalStack())

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[0 1 2 3 4 5 6 7 8 9]


# Part 2

In [59]:
a = np.array(np.random.randint(1,50,10))
a.sort()
b = np.array(np.random.randint(1,50,10))
b.sort()
print()
def Intersect(a,b):
    print(f"a = {a}")
    print(f"b = {b}")
    return np.intersect1d(a,b)
print(f"Comman Values are : {Intersect(a,b)}")


a = [14 22 24 27 33 35 40 44 45 48]
b = [ 2  3  5  6  6 10 14 23 35 41]
Comman Values are : [14 35]


In [61]:
def Differance(a,b):
    print(f"a = {a}")
    print(f"b = {b}")
    return np.setdiff1d(a,b)
print(Differance(a,b))

a = [14 22 24 27 33 35 40 44 45 48]
b = [ 2  3  5  6  6 10 14 23 35 41]
[22 24 27 33 40 44 45 48]


In [67]:
def ReverseColums():
    print(OneDToTwoD())
    print()
    return np.flip(OneDToTwoD(),axis=1)
print(ReverseColums())

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[4 3 2 1 0]
 [9 8 7 6 5]]


In [71]:
def TwoDArray():
    arr2d = np.array(np.random.uniform(5,10,15)).reshape(5,3)
    return arr2d
print(TwoDArray())

[[9.1925973  9.87014295 6.80371195]
 [5.37628419 8.26357121 7.90301817]
 [9.81584211 6.02430585 6.48249506]
 [8.33058378 5.94774899 7.41670603]
 [8.79273273 8.58108789 5.62872505]]


In [28]:
def matrix():
    ar = np.zeros((5,5),dtype=int)
    main_diag_indices = np.diag_indices_from(ar)
    row_indices = main_diag_indices[0][1:]  # 1 2 3 4   1,0=1 2,1=2 3,2= 3 
    col_indices = main_diag_indices[1][:-1] # 0 1 2 3
    ar[row_indices, col_indices] = [1, 2, 3, 4]
    return ar
print(matrix())

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Part 3

In [77]:
def pattren():
    a = np.array([1,2,3])
    print(np.hstack((np.repeat(a,3),a,a)))
pattren()

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
