# UFUNCS in NumPy

##### There are the Functions that are used to make the code easy and more effective.

##### ufuncs exist in two flavours : 1. unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs.

###### .Array Arithmetic.

###### arr = np.add(x,2)

###### .Absolute value

###### arr = np.abs(x)

###### .Trignometric Functions.

###### arr = np.sin(x)

###### .Exponent and logarithms

###### arr = np.exe(x)

###### arr = np.beta(x)

###### .Summing Arrays.

###### arr = np.sum(array_name)

In [22]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

In [24]:
print(np.add(arr1,arr2))

[ 3  7 11 15 19]


In [34]:
print(np.lcm.reduce(arr1))

315


In [36]:
print(np.abs(arr1))

[1 3 5 7 9]


In [38]:
print(np.fabs(arr1))

[1. 3. 5. 7. 9.]


In [3]:
import pandas as pd
print(pd.__version__)

2.2.2
