In [2]:
import numpy as np

In [10]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
ans = np.add(array1,array2)
print(ans)

[ 6  8 10 12]


In [12]:
print(np.lcm.reduce(array1))

12


In [16]:
a =12
b = 2
print(np.lcm(a,b))

12


In [22]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = np.add(x, y)  # array([5, 7, 9])
print(result)


[5 7 9]


In [24]:
x = np.array([5, 6, 7])
y = np.array([1, 2, 3])
result = np.subtract(x, y)  # array([4, 4, 4])
print(result)

[4 4 4]


In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = np.multiply(x, y)  # array([ 4, 10, 18])
print(result)

[ 4 10 18]


In [28]:
x = np.array([8, 6, 4])
y = np.array([2, 3, 4])
result = np.divide(x, y)  # array([4. , 2. , 1. ])
print(result)

[4. 2. 1.]


In [30]:
base = np.array([2, 3, 4])
exponent = np.array([3, 2, 1])
result = np.power(base, exponent)  # array([ 8,  9,  4])
print(result)

[8 9 4]


In [32]:
x = np.array([4, 9, 16])
result = np.sqrt(x)  # array([2., 3., 4.])
print(result)

[2. 3. 4.]


In [35]:
x = np.array([1, 2, 3])
result = np.exp(x)  # array([ 2.71828183,  7.3890561 , 20.08553692])
print(result)

[ 2.71828183  7.3890561  20.08553692]


In [37]:
x = np.array([1, np.e, np.e**2])
result = np.log(x)  # array([0., 1., 2.])
print(result)

[0. 1. 2.]


In [39]:
x = np.array([0, np.pi/2, np.pi])
result = np.sin(x)  # array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])
print(result)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [41]:
x = np.array([0, np.pi/2, np.pi])
result = np.cos(x)  # array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00])
print(result)

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [43]:
x = np.array([0, np.pi/4, np.pi/2])
result = np.tan(x)  # array([0.0000000e+00, 1.0000000e+00, 1.6331239e+16])
print(result)

[0.00000000e+00 1.00000000e+00 1.63312394e+16]


In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
result = np.maximum(x, y)  # array([3, 2, 3])
print(result)

[3 2 3]


In [47]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
result = np.minimum(x, y)  # array([1, 2, 1])
print(result)

[1 2 1]


In [51]:
x = np.array([-1, -2, 3])
result = np.abs(x)  # array([1, 2, 3])
print(result)

[1 2 3]


In [59]:
import pandas as pd
s = pd.Series()
print(s)

Series([], dtype: object)


In [61]:
a = pd.Series([1,2,3,4])
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [63]:
print(a.values)

[1 2 3 4]


In [65]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [71]:
print(a[3])

4


In [73]:
b = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(b)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [75]:
print(b[2])

3


C:\Users\M Hamza Mirani\AppData\Local\Temp\ipykernel_18368\277079519.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[2])


In [77]:
print(b["e"])

5


In [81]:
c = pd.Series([1,2,3,4,5],index=["c","b","d","a","e"])
print(c)

c    1
b    2
d    3
a    4
e    5
dtype: int64


In [85]:
print(c["d"])

3


In [91]:
import numpy as np
import pandas as pd
data = {'a':0,'b':1,'c':2}
d = pd.Series(data)
print(d)

a    0
b    1
c    2
dtype: int64


In [93]:
dict = {
    'name':['Asad', 'Hanan', 'Shoaib'],
    'marks':[45, 50, 47],
    'age':[21,20,21],
    'cast':['Merani', 'Choudary', 'Baloch']
}

df = pd.DataFrame(dict)
print(df)

     name  marks  age      cast
0    Asad     45   21    Merani
1   Hanan     50   20  Choudary
2  Shoaib     47   21    Baloch


In [95]:
f = pd.Series(3,index = [0,1,2,3])
print(f)

0    3
1    3
2    3
3    3
dtype: int64
