In [3]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the mean along the specified axis
mean_value_axis0 = np.mean(array, axis=0)  # Mean along columns
mean_value_axis1 = np.mean(array, axis=1)  # Mean along rows

print("Mean along axis 0:", mean_value_axis0)
print("Mean along axis 1:", mean_value_axis1)


Mean along axis 0: [2.5 3.5 4.5]
Mean along axis 1: [2. 5.]


In [5]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Calculate the variance of the array elements
variance = np.var(array)

print(variance)


2.0


In [7]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the variance along the specified axis
variance_axis0 = np.var(array, axis=0)  # Variance along columns
variance_axis1 = np.var(array, axis=1)  # Variance along rows

print("Variance along axis 0:", variance_axis0)
print("Variance along axis 1:", variance_axis1)


Variance along axis 0: [2.25 2.25 2.25]
Variance along axis 1: [0.66666667 0.66666667]


In [13]:
import numpy as np

# Create a NumPy array
array = np.array([1, 3, 2, 5])

# Compute the cumulative maximum using np.maximum.accumulate
cumulative_max = np.maximum.accumulate(array)

print(cumulative_max)


[1 3 3 5]


In [21]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6])

# Define a condition
condition = array > 3

# Find indices where the condition is True
indices = np.where(condition)

print(indices)


(array([3, 4, 5], dtype=int64),)


In [23]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Define a condition
condition = array > 3

# Find indices where the condition is True
indices = np.where(condition)

print(indices)


(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))


In [32]:
import numpy as np

# This will create an array of ones, not filled with 7
array = np.ones((4, 3), dtype='i') * 7
print(array)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [30]:
import numpy as np

# Create an array of shape (4, 3) filled with the value 7
array = np.full((4, 3), 7)

print(array)
# Output:
# [[7 7 7]
#  [7 7 7]
#  [7 7 7]
#  [7 7 7]]


[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [34]:
import numpy as np

# Create a 5x5 identity matrix
matrix = np.identity(5)

print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
import numpy as np

matrix = np.eye(5)

print(matrix)
print(type(matrix))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [44]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
clipped_arr = np.clip(arr, 3, 6)
print(clipped_arr)  # Output: [2, 2, 3, 4, 4]


[3 3 3 4 5 6 6 6 6]


In [58]:
a = np.random.rand(10)
print(a)

[0.21433226 0.92429793 0.00116403 0.30271151 0.67226838 0.72352951
 0.5781205  0.82317525 0.85190062 0.82440291]


In [60]:
a = np.random.random(10)
print(a)

[0.61530205 0.50941416 0.79343812 0.76899589 0.77834121 0.3632912
 0.26633052 0.98197721 0.01704973 0.57382041]


In [62]:
a = np.random.randn(10)
print(a)

[ 1.68577803  0.6861046   0.25447264 -0.04987913 -0.47155494 -1.79741553
 -0.9659885  -2.07850524 -2.06609362  0.31343034]
